version: '3.8'

services:
  mysql:
    image: mysql:latest  # MySQLの最新版を使用
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./sql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres:latest  # PostgreSQLの最新版を使用
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# データを永続化するためにボリュームを定義
volumes:
  mysql-data:
  postgres-data: